name: Test
on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
      - 'Dockerfile'
      - '.github/workflows/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install npm
        working-directory: src
        run: npm i
      - name: Run test
        working-directory: src
        run: npm run test